# -*- coding: utf-8 -*-
"""Projeto Final - Quiz Geográfico

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnH6fX9tTFfsjYittD1nnQUqvKT3z6Va
"""

#Bibliotecas utilizadas no código
import math
import pandas as pd
import os

#Introdução do Quiz (regras + inserção do nickname do jogador)
print("====== QUIZ DE GEOGRAFIA ======")

nome_jogador = str(input("Insira seu nome: "))

print(f"Bem vind@, {nome_jogador}! Você está prestes a jogar o Quiz de Geografia, mas antes disso, aqui estão as regras:")
print("A cada acerto você GANHA 10 pontos")
print("A cada erro vocẽ PERDE 5 pontos")
print("Para responder, insira APENAS a LETRA que represente a alternativa (ex.: A)")
print("O quiz possui três MODALIDADES: CURTA (5 questões), MÉDIA (10 questões) e LONGA (15 questões)")
print("Bom jogo!")

#Funções empregadas no código
def resultado(resposta, alt_correta):
  """Compara a resposta inserida pelo jogador com a resposta registrada no dicionário de questões e diz se está certa ou errada

  Args:
    resposta (str): alternativa inserida pelo jogador na questão atual
    alt_correta (str): a alternativa correta armazenada no dicionário de questôes

  Returns:
    "Resposta Correta :)": quando o jogador acerta
    "Resposta Incorreta :(": quando o jogador erra
  """
  if resposta == alt_correta:
    return "Resposta Correta :)"
  else:
    return "Resposta Incorreta :("

def placar(pontos, resposta, alt_correta):
  """Calcula a pontuação de acordo com cada acerto/erro

  Args:
    pontos (int): a pontuação do jogador antes da questão atual
    resposta (str): a alternativa inserida pelo jogador na questão atual
    alt_correta (str): a alternativa correta armazenada no dicionário de questôes

  Returns:
    pontuacao (int): a pontuação do jogador após respinder a questão atual
  """
  if resposta == alt_correta:
    pontuacao = pontos + 10
  else:
    pontuacao = pontos - 5
  print(f"Pontuação: {pontuacao}")
  return pontuacao

#Dicionário de questões (perguntas/alternativas + alternativa correta)
dic_questoes = [
    {
        "pergunta": "Quais são, respectivamente, o menor e o maior continente do mundo?",
        "opcoes": {
            "A": "Europa e África",
            "B": "Oceania e Ásia",
            "C": "Antártida e América",
            "D": "Europa e América",
            "E": "África e Ásia"
        },
        "alt_correta": "B"
    },
    {
        "pergunta": "Qual é o maior deserto do mundo?",
        "opcoes": {
            "A": "Deserto do Saara",
            "B": "Deserto da Arábia",
            "C": "Deserto do Atacama",
            "D": "Deserto da Antártida",
            "E": "Deserto de Gobi"
        },
        "alt_correta": "D"
    },
    {
        "pergunta": "Quais são os pontos colaterais da rosa dos ventos?",
        "opcoes": {
            "A": "Nordeste, Sudeste, Noroeste e Sudoeste",
            "B": "Norte, Sul, Leste e Oeste",
            "C": "Norte, Nordeste, Leste e Sudeste",
            "D": "Sul, Sudeste, Oeste e Noroeste",
            "E": "Norte, Sul, Nordeste e Sudoeste"
        },
        "alt_correta": "A"
    },
    {
        "pergunta": "Quais são os principais tipos de relevo encontrados no Brasil?",
        "opcoes": {
            "A": "Cordilheiras, fiordes e desertos",
            "B": "Planaltos, dunas e vulcões",
            "C": "Depressões, geleiras e montanhas",
            "D": "Montanhas, vales e depressões",
            "E": "Planícies, planaltos e depressões"
        },
        "alt_correta": "E"
    },
    {
        "pergunta": "Quais países fazem fronteira com o Brasil?",
        "opcoes": {
            "A": "França, Espanha, Portugal e Itália",
            "B": "Alemanha, Bélgica, Holanda e Suíça",
            "C": "México, Estados Unidos, Canadá e Cuba",
            "D": "Argentina, Uruguai, Paraguai e Bolívia",
            "E": "Japão, China, Coreia do Sul e Mongólia"
        },
        "alt_correta": "D"
    },
    {
        "pergunta": "O que é densidade demográfica?",
        "opcoes": {
            "A": "O número total de habitantes de um país",
            "B": "A taxa de natalidade de uma população",
            "C": "A quantidade de cidades existentes em um território",
            "D": "A relação entre o número de habitantes e a área de um território",
            "E": "O crescimento populacional ao longo dos anos"
        },
        "alt_correta": "D"
    },
    {
        "pergunta": "Qual é o país menos populoso do mundo?",
        "opcoes": {
            "A": "Vaticano",
            "B": "Narau",
            "C": "Mônaco",
            "D": "Liechtenstein",
            "E": "Malta"
        },
        "alt_correta": "A"
    },
    {
        "pergunta": "Qual é a importância do Meridiano de Greenwich?",
        "opcoes": {
            "A": "Ele marca a Linha do Equador e divide os hemisférios Norte e Sul",
            "B": "Ele define os limites entre continentes e oceanos",
            "C": "Ele determina as estações do ano no planeta",
            "D": "Ele serve como referência para a contagem dos fusos horários no mundo",
            "E": "Ele distancia os trópicos um do outro"
        },
        "alt_correta": "D"
    },
    {
        "pergunta": "A Guerra Fria foi um período de tensão vivenciado pelo mundo em parte do século XX, em razão da disputa política, econômica e ideológica entre as duas grandes potências mundiais da época. Quais eram os dois países diretamente envolvidos na Guerra Fria?",
        "opcoes": {
            "A": "Israel e Emirados Árabes Unidos",
            "B": "Turquia e Grécia",
            "C": "Estados Unidos e União Soviética",
            "D": "Reino Unido e França",
            "E": "China e Japão"
        },
        "alt_correta": "C"
    },
    {
        "pergunta": "A política de Guerra ao Terror, empreendida pelos Estados Unidos no início do século XXI, culminou em um dos mais importantes conflitos geopolíticos recentes. Esse conflito ficou conhecido como a",
        "opcoes": {
            "A": "Guerra da Coreia",
            "B": "Guerra da Crimeia",
            "C": "Guerra do Vietnã",
            "D": "Guerra do Afeganistão",
            "E": "Guerra da Síria"
        },
        "alt_correta": "D"
    },
    {
        "pergunta": "No período conhecido como Guerra Fria, o cenário geopolítico mundial apresentava-se bipolarizado entre os blocos liderados pelos Estados Unidos e pela União Soviética. No plano militar, esses blocos formaram",
        "opcoes": {
            "A": "a Organização do Tratado do Atlântico Norte e o Pacto de Varsóvia",
            "B": "a Conferência de Bretton Woods e o Grupo dos Oito",
            "C": "o Mercado Comum Europeu e o Conselho de Ajuda Econômica Mútua",
            "D": "o Grupo dos Sete e a Comunidade dos Estados Independentes",
            "E": "o Comitê de Forças Armadas e a Comissão de Consolidação da Paz"
        },
        "alt_correta": "A"
    },
    {
        "pergunta": "Sobre a geopolítica energética, é correto afirmarmos:",
        "opcoes": {
            "A": "Algumas das principais áreas produtoras de petróleo encontram-se, no Oriente Médio, na África e na América Latina, isso devido ao predomínio de rochas cristalinas nas estruturas geológicas dessas regiões",
            "B": "A participação do petróleo no conjunto das fontes energéticas vem crescendo lentamente, enquanto a de outras fontes vem decaindo",
            "C": "A recente crise dos Estados Unidos com o Irã, com a iminência de uma guerra, poderá trazer consequências favoráveis ao mundo, com a baixa do preço do petróleo",
            "D": "Em meados do século XVIII, a Inglaterra foi palco da Revolução Industrial. Vários motivos contribuíram para esse fato, entre os quais, a posse de grandes recursos energéticos como o carvão mineral, que, sem dúvida alguma, contribuiu muito para a eclosão da Revolução Industrial",
            "E": "A recente crise do Golfo Pérsico, com a iminência de uma guerra, poderá trazer consequências favoráveis ao mundo, como a baixa do preço do petróleo do Iraque"
        },
        "alt_correta": "D"
    },
    {
        "pergunta": "A China, mediante o seu crescimento político e econômico, é um dos principais atores geopolíticos da atualidade. Uma das estratégias utilizadas pelos chineses no aumento da sua área de influência é a",
        "opcoes": {
            "A": "ocupação de partes do território da Rússia",
            "B": "criação de ilhas artificias em áreas marítimas da Ásia",
            "C": "construção de muros na divisa com a Índia",
            "D": "dominação do controle de tráfego do Canal do Panamá",
            "E": "exploração de petróleo na Floresta Amazônica"
        },
        "alt_correta": "B"
    },
    {
        "pergunta": "O português não é um idioma oficial em qual destes países? ",
        "opcoes": {
            "A": "Brasil",
            "B": "Nicarágua",
            "C": "Portugal",
            "D": "Guiné-Bissau",
            "E": "Angola"
        },
        "alt_correta": "B"
    },
    {
        "pergunta": "Qual a capital da Guatemala?",
        "opcoes": {
            "A": "Guatemala",
            "B": "La Paz",
            "C": "São Tomé",
            "D": "Porto Príncipe",
            "E": "Cidade da Guatemala"
        },
        "alt_correta": "A"
    },
    {
        "pergunta": "Quantos países tem a América?",
        "opcoes": {
            "A": "29",
            "B": "40",
            "C": "35",
            "D": "43",
            "E": "37"
        },
        "alt_correta": "E"
    },
    {
        "pergunta": "A que país pertencem as Ilhas Canárias?",
        "opcoes": {
            "A": "Portugal",
            "B": "França",
            "C": "Países Baixos",
            "D": "Espanha",
            "E": "Inglaterra"
        },
        "alt_correta": "D"
    },
    {
        "pergunta": "Qual cidade é a mais densamente povoada do mundo?",
        "opcoes": {
            "A": "Mumbai",
            "B": "Mandaluyong",
            "C": "Manila",
            "D": "Bagdá",
            "E": "Istambul"
        },
        "alt_correta": "C"
    },
    {
        "pergunta": "Qual país abriga o Monte Everest?",
        "opcoes": {
            "A": "Butão",
            "B": "Nepal",
            "C": "Bangladesh",
            "D": "China",
            "E": "Índia"
        },
        "alt_correta": "B"
    },
    {
        "pergunta": "La Sagrada Familia é um famoso marco da Espanha. Em que cidade está localizado?",
        "opcoes": {
            "A": "Barcelona",
            "B": "Granada",
            "C": "Valência",
            "D": "Madrid",
            "E": "Sevilha"
        },
        "alt_correta": "A"
    },
    {
        "pergunta": "Quantos países ainda têm o xelim como moeda?",
        "opcoes": {
            "A": "0",
            "B": "1",
            "C": "2",
            "D": "3",
            "E": "4"
        },
        "alt_correta": "E"
    },
    {
        "pergunta": "Quanto da superfície da Terra é coberta pelo oceano?",
        "opcoes": {
            "A": "82%",
            "B": "75%",
            "C": "67%",
            "D": "71%",
            "E": "80%"
        },
        "alt_correta": "D"
    },
    {
        "pergunta": "A Geopolítica é um campo de estudo que remete às relações entre os países. Atualmente, a lógica geopolítica global é marcada pela",
        "opcoes": {
            "A": "unipolaridade",
            "B": "monarquia",
            "C": "bipolaridade",
            "D": "democracia",
            "E": "multipolaridade"
        },
        "alt_correta": "E"
    },
    {
        "pergunta": "O Conflito Israel-Hamas fez revigorar a discussão do aspecto expansionista territorial israelense no que suas lideranças políticas, militares e religiosas mais ortodoxas reivindicam ser seu o direito à autodeterminação em seu solo pátrio, razão pela qual defendem a colonização de áreas até então ocupadas desde longa data pelos palestinos. O movimento que tem tais conotações territorialmente expansionistas é denominado de",
        "opcoes": {
            "A": "semitismo",
            "B": "assimilação",
            "C": "sionismo",
            "D": "judaísmo",
            "E": "nenhuma das alternativas"
        },
        "alt_correta": "C"
    },
    {
        "pergunta": "Recentemente, houve um ataque à região de Nagorno-Karabakh, reacendendo, em 2023, tensões geopolíticas na região. Sobre o conflito é correto afirmar:",
        "opcoes": {
            "A": "o conflito hoje reacende disputas entre Rússia e Japão, que tentam se legitimar na região",
            "B": "desde 1990, é a primeira vez que o cessar-fogo é interrompido",
            "C": "o conflito na região ocorre entre Armênia e Afeganistão, originado desde o colapso da União Soviética",
            "D": "a Armênia recebe apoio dos Estados Unidos, que financia a guerra por meio de armas",
            "E": "envolvida na Guerra das Maldivas, a Rússia tem mantido distância do conflito, potencializando as disputas na região"
        },
        "alt_correta": "C"
    }
]

#Conversão do dicionário em DataFrame por meio do Pandas para gerar as questões em ordem aleatória
df_dic = pd.DataFrame(dic_questoes)
df_embaralhado = df_dic.sample(frac=1)

#Estruturas de controle (if/elif + while) para definir as 3 modalidades do quiz
modalidade = ''
while modalidade not in ['CURTA', 'MÉDIA', 'LONGA']:
    modalidade = str(input("Insira a modalidade desejada: ")).upper()
num_questoes = 0
if modalidade == 'CURTA':
    num_questoes = 5
elif modalidade == 'MÉDIA':
    num_questoes = 10
elif modalidade == 'LONGA':
    num_questoes = 15

#Loops usados para:
pontos = 0.0
for index, row in df_embaralhado.head(num_questoes).iterrows(): #exibir apenas o número de questões selecionadas (modalidade)
    print(row['pergunta'])
    for option_key, option_value in row['opcoes'].items(): #ler as questões corretamente e garantir iteração
        print(f"{option_key}) {option_value}")
    resposta = str(input("Digite a alternativa: ")).upper()
    alt_correta = row['alt_correta']

    print(resultado(resposta, alt_correta))
    pontos = placar(pontos, resposta, alt_correta) #atualizar a pontuação

print(f"Pontuação final: {pontos}")

#Salva as pontuações dos jogadores em um arquivo CSV
ranking_df = pd.DataFrame([{'Jogador': nome_jogador, 'Pontuação': pontos}])
arquivo_existente = os.path.isfile('ranking.csv')
ranking_df.to_csv('ranking.csv', mode='a', header=not arquivo_existente, index=False)

#Armazenamento associado dos jogadores e suas pontuações para montar o ranking
print('=== RANKING ===')
historico_ranking = [] #Lista multidimensional que monta o ranking
if os.path.isfile('ranking.csv'):
    with open('ranking.csv', 'r', encoding='utf-8') as ranking_arq:
        lines = ranking_arq.readlines()
        if len(lines) > 0 and lines[0].strip() == 'Jogador,Pontuação':
            linha = lines[1:]

        for linha in lines: #iteração as linhas do arquivo
            try:
                jogador, pontuacao_str = linha.strip().split(',')
                historico_ranking.append([jogador, float(pontuacao_str)])
            except ValueError:
                continue

historico_ranking.sort(key=lambda x: x[1], reverse=True) #ordena o ranking

for i, (jogador, pontos_jogador) in enumerate(historico_ranking): #iteração da lista multidimensional
    print(f'{i+1}. {jogador}: {pontos_jogador} pontos')

#Tupla que contém a bibliografia do quiz
biblio_tupla = ("www.vestibulares.estrategia.com/portal/atualidades-e-dicas/questoes-sobre-geopolitica/", "www.todamateria.com.br/24-perguntas-de-conhecimentos-gerais-de-geografia-com-respostas/", "www.exercicios.brasilescola.uol.com.br/exercicios-geografia/exercicios-sobre-geopolitica.htm")
print("Deseja ver a bibliografia para ter acesso a mais questões? Digite SIM. Caso contrário, digite NÃO.")
bibliografia = str(input()).upper()
if bibliografia == 'SIM': #opção de exibição da tupla
  print("=== BIBLIOGRAFIA ===")
  print(biblio_tupla)

#Finalização do quiz
print("Obrigada por jogar! Até a próxima!")